name: Docker Image CI for GHCR

on:
    push:
        branches:
            - develop

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build and push Docker image to GHCR
            run: |
                docker login ghcr.io -u ${{ github.actor }} --password-stdin
                docker build -t ghcr.io/${{ github.repository }}:latest .
                docker push ghcr.io/${{ github.repository }}:latest